modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL="${issue_tracker_url}" #optional
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="" #optional
displayURL = "${display_url}" #optional
logoFile = "${logo_file}" #optional
credits = "${credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''
#displayTest=""

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
side="BOTH" # Physical side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"